= CCUF Charter and Policies
:showtitle:
:imagesdir: images
:revnumber: 2.0
:revdate: September 22, 2020
:xrefstyle: short

== CCUF Principles
=== Mission
The Common Criteria Users’ Forum mission is to provide a voice and communications channel between the CC community and the Common Criteria organizational committees, CCRA member organizations (national schemes), and policy makers. In order to further the CCUF mission, our objectives are to improve and promote Common Criteria by seeking to

* Support and foster the goal of worldwide mutual recognition.
* Promote focused international Technical Communities and technical working groups, to enable the creation of useful, realistic, internationally-recognized protection profiles, supporting documents, and advance Common Criteria.
* Help to assure customers of evaluated products with meaningful evaluation results.
* Encourage viable policies and processes for maintaining certification through product updates.
* Encourage viable policies and processes for certifying systems that are composed of certified parts.
* Minimize the time, effort, and cost required to complete evaluations which lead to appropriate levels of assurance.

=== Principles of Operation
* The CCUF will seek to operate within the guidance of these Principles and will refrain from actions, or inactions, which would contradict these Principles.
* The CCUF will be independent of any government or certification body.
* The CCUF will provide an open forum for a broad spectrum of participants.
* The CCUF will accept any member who joins and participates in good faith.
* The CCUF will not favour any group or interest within its membership.
* The CCUF will consider the expression and consideration of minority opinions and interests.
* The CCUF may address issues which are also being addressed by other organisations or groups.
* The CCUF will maintain its independence and identity in order to adhere to these principles.
* The CCUF will remain vigilant to ensure that no one group acquires undue influence within the CCUF which would contravene these Principles.
* CCUF members must not take part in discussions which may give rise to accusations of collusion, monopolistic, anti-trust or anti-competitive behaviour.
* The CCUF should not allow the discussion of inappropriate topics and should encourage its members to formally object to such discussions.  Any complaints about such inappropriate discussions should be sent to mgmt@ccusersforum.org.

== CCUF Rules
:sectnums:

== Membership

. Membership of the CCUF is open to all individuals with an interest in the Common Criteria.  If the individual has an affiliation with an organization/entity, the individual must declare this and report any changes to their affiliation. 
. The list of individual user accounts used by CCUF collaboration tools defines the membership roster for the CCUF and the technical communities and working groups within the CCUF. 
. CCUF members are expected to follow the CCUF Principles of Operation.

== Meetings
. The CCUF will have at least two membership meetings each year.
. The CCUF will work to facilitate in-person meetings for members every year. 
. The CCUF will support virtual meetings every year if in-person meetings are not feasible.

== Management Group (MG)
. The role of the CCUF MG is to operate the CCUF in accordance with the Principles.
. The CCUF MG will meet (usually via teleconference) on a monthly basis or as agreed within the CCUF MG.
. The MG will maintain and publish Policies and Procedures for its own operation and for the administration of the CCUF, which are more fluid, whereas the Principles and Rules specified in this governance document are foundational items that change less frequently.
. When the CCUF MG develops proposed Principles, Rules, Policies, and Procedures they will be checked to ensure compliance with the CCUF Principles of Operation.
. The member organizations that comprise the CCUF approve the Principles and Rules; the CCUF MG approves the Policies and Procedures.
. The Management Group will vote on proposed policies and procedures which must pass by simple majority and inform the general CCUF membership.
. MG Composition
.. The Management Group (MG) consists of at least three and no more than seven elected members from the CCUF membership and one liaison from the CC Development Board (CCDB).
.. Because the CCDB is represented by a liaison to the CCUF MG, CCUF members from CCRA member organizations are not eligible to serve on the CCUF MG.footnote:[The list of CCRA Member organizations is at http://www.commoncriteriaportal.org/ccra/members/.]
.. [[members]]There shall not be more than 2 CCUF MG members from any one organization.
.. Membership of the CCUF MG is on a personal basis rather than an organizational basis.  Thus any CCUF MG member who changes to another organization may remain a CCUF MG member, subject to not breaching the “no more than 2 individuals from one organisation” rule <<members,3.7.c>>.
.. The MG roles are a Chair, a Vice-Chair, and other roles as decided by the MG. There may also be additional roles appointed by the Management Group for CCUF members.  Appointed roles do not vote on matters before the MG.
. MG Elections 
.. There are no requirements to be elected to the CCUF MG other than the willingness to operate in accordance with the CCUF Principles.
.. Members of the Group are elected for a 2 year term of office, with elections held in April/May of even calendar years for all 7 seats.footnote:[This transition was done to eliminate the disruption of holding an election every year.]
.. Individuals on the CCUF MG may stand for re-election with no limit on the number of times that a person may be re-elected.
.. If a member of the CCUF MG resigns or is not eligible to serve, then the CCUF MG may hold a special election for that seat or leave the seat vacant if approaching an election cycle.

== Voting
The CCUF membership will be asked to vote on issues which affect the operation of the CCUF.  Only the CCUF MG can initiate a vote, but any member may request that the MG consider a vote on a subject.  Voting by the general CCUF membership will be held when there are changes to the CCUF Principles, Rules, and elections to the Management Group. 

. Before voting commences the CCUF MG will notify the CCUF Membership of the purpose of the vote and the timeline (for example, a freeze date for eligible voting entities, dates when nominations will open and close, when voting will start and finish, and when results will be announced and will take effect).
. General rules of CCUF voting are:
.. Voting will be one (1) vote per ‘entity’ (Entity is the organization associated with that user’s profile, or individual member who is not affiliated with any CCUF member organization).  Only individual members who are not affiliated with any CCUF member organization can vote as an individual.
... For CCUF MG elections, each entity can cast a ballot with up to seven (7) different nominated candidates with no duplicate names on the ballot. 
.. If more than one vote is received from an entity the first ballot cast will be used and the sender of the first and second ballot will be informed of the duplicate ballot.  
.. [[Votes]]Voting will take place during a period of a minimum of one week, starting on Wednesday and ending no earlier than the following Tuesday in order to allow for enough time for all entities to vote. Specific start and end times for voting (including the time zone) will be announced by the CCUF MG.  The announcement of the upcoming vote will be posted on the CCUF Forum. The announcement will be made at a minimum 6 weeks before the actual vote.
.. Voting will take place by email. The email address for voting will be announced by the CCUF MG.
.. In order for ballot email to count it must include the entity name and the name of the person casting the vote (but voter’s name will not be tracked along with the actual vote, only that their entity has voted and the person’s contact information).
..  For any modifications to the CCUF Charter - Principles and Rules section the modification is proposed and the vote will be between accepting this proposal or not. Changes to the CCUF Charter   Principles and Rules section will not be proposed with multiple options to ensure a clear vote to accept the proposal or not.  For any modifications to the CCUF Charter   Principles and Rules section the proposed change must receive a supermajority of the votes, defined as at least 2/3 of the votes in favor of the modification to pass.
.. For any modifications that do not impact the CCUF Charter   Principles and Rules section, votes in favor or against a change as well as votes between two options or votes between more than two options are possible. For votes about a change, a simple majority of the eligible votes cast, will determine if the proposed change is accepted or not.  For votes between two options, a simple majority of the eligible votes cast, will determine which of the options will be chosen. For votes with more than two options, the option with the most votes will be chosen. When voting for election to the Management Group, the candidates that receive the plurality of eligible votes will be chosen for the Management Group. 
.. In the case of a tie there will be a runoff vote using the same rules. 
.. Results will list the number of votes cast for each choice, and will separately list the entities that cast votes. Results will not show which entities cast votes for which choices, nor will they list the individuals who represented the voting entities. 
.. Vote counters (at minimum three) will be volunteers appointed by the CCUF MG, and no vote counter should have a significant interest in the outcome of the vote (for example, they are standing for election, or they have been the main proponent of an issue that subject to a vote or be from the same organization as a nominee running for a position).
.. The MG will announce additional voting procedures at the same time as the voting announcement <<Votes>>. For example, when the vote is for the seven seats on the MG each entity will be allowed to vote for up to seven different candidates (but not more than once for any candidate).
... In the case where there are seven (or fewer) candidates for the MG, the candidates will be considered as having been elected without the need for a full membership vote.
. The MG will announce additional voting procedures at the same time as the announcement.

:sectnums!:
== Policies and Procedures
:sectnums:
== Membership
There are no additional policies beyond the rules outlined in Rules Section 1.

== Meetings and Workshops
. The CCUF will endeavour to have face to face meetings at least twice yearly. When an in-person meeting is are not feasible, the CCUF will support a virtual meetings in its place. It is likely that one of the meetings will be a Workshop prior to the annual International Common Criteria Conference, and the other will be a Workshop during the first quarter CCDB meetings or a meeting at the San Francisco RSA Conference. The CCUF MG may decide to vary these arrangements and provide advance notice to the Membership.
. Draft Agendas for CCUF meetings will be published by the MG and CCUF members will be able to request additional items to be added to the agenda.
. Working Groups and Technical Working Groups
.. A Working Group (WG) seeks to improve the CCUF; and any CCUF member can start a WG by informing the MG of their intent and allowing any interested CCUF members to join the Working Group. Working Groups can choose to meet separately or meet as part of a CCUF workshop.
.. A Technical Working Group (TWG) seeks to improve the CC; and any CCUF member can start a TWG by informing the MG and the CCDB liaison of their intent and allowing any interested CCUF members to join the Technical Working Group. Technical Working Groups can choose to meet separately or meet as part of a CCUF workshop.
.. WGs and TWGs can use any available CCUF resources such as the CCUF web portal and meeting spaces at CCUF workshops.
.. WGs and TWGs should have a liaison to the CCUF MG to provide information about the group’s membership and activities.
. Technical Communities and International Technical Communities
“International Technical Communities” are organizations that develop collaborative protection profiles and supporting documents, with the latter being approved by the CCDB. “Technical Communities” are all other groups that develop protection profiles and are not iTCs.
.. All Technical Communities (TC) and international Technical Communities (iTC) should follow the CCUF Mission as they develop Common Criteria Protection Profiles and Supporting Documents.
.. All TCs and iTCs can use any available CCUF resources such as the CCUF web portal and meeting spaces at CCUF workshops.
.. TCs and iTCs should have a liaison to the CCUF MG to provide information about the TC and iTC membership and activities.

== Management Group (MG)
. CCUF Communications 
.. The CCUF MG will publish, via the CCUF website, notes of CCUF general meetings (including all face to face meetings) and MG meetings.
.. The MG may also publish requests for comment or information, blogs, or other items of potential interest to the membership of the CCUF on the CCUF website.
.. The MG will also publish information, such as dates of proposed meetings.
.. It is possible that some material may be provided to the MG on the basis that it is not disseminated further (e.g. from the CCDB).  In such cases the meeting minutes will note that some information has been withheld at the request of the originator.
.. Documents produced by the MG may be posted for review so interested CCUF members may provide comments for a limited time.  Review comments will be taken into account by the document author(s) when developing subsequent versions.  Where comments are not incorporated into the text of the subsequent version CCUF members may seek clarification of the reasons for such action.
.. As and when the MG develops proposed new Rules, Policies, or Procedures they will be checked to ensure compliance with the CCUF Principles of Operation.
.. Where the MG considers that potential Policies or Procedures may have a significant impact on the overall CCUF then a vote of the CCUF membership shall be sought on the adoption of such additional rules.

. CCUF MG Tasks
.. The allocation of tasks within the MG will be by agreement of the MG.
.. When the MG seeks assistance with the tasks, then a sub-group may be formed to carry out one or more identified pieces of work.  Such sub-groups will be free to choose their method of operations, within the CCUF Principles of Operation, subject to direction from the MG.  A member of the MG will be the MG liaison for the sub-group.
.. Outputs from sub-groups and Technical Working Groups will be provided to the CCUF MG who will decide on future work or publication of results.

. MG Voting
.. Where votes are required within the MG then majority voting applies, with a quorum of two-thirds (2/3), rounding up, CCUF MG members participating.
.. Where voting would not be quorate then interim votes may be held for subsequent ratification or rejection at the next meeting.
.. Outcomes of MG voting will be recorded in meeting notes which will be published on the CCUF website.

== Voting
. There are no additional policies beyond the rules outlined in Rules <<Voting>>.

== Organization Status
. The CCUF is an unincorporated non-profit association.